dep=card.cpp card.h cli_interface.cpp cli_interface.h game.cpp hand.h interface_choices.h player.h player.cpp shoe.cpp shoe.h table.cpp table.h user.cpp user.h

all:
	gcc main.cpp -o balackjack $(dep) -lm

